# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1abc5f45ae00d5f604b8e354d51882b65ce96853692a07879740ce092382b2c3fbad32a5481aee66a5b878d6f7272a026557ef4a39f9ab929345503f207a9a82

test:
  secret_key_base: 1cc1facb929d752ba609394e0a55c200f48abcd25dabf2cc358adab7bbe5aa35eb75e9fe81c6c7690cff85d672fe12e139cd92952d76381b399d4411dc6a474d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
